"""Add original_name to Audio and Video

Revision ID: 4e2acfb1df17
Revises: 96c9547de47e
Create Date: 2025-11-27 00:22:35.925434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2acfb1df17'
down_revision = '96c9547de47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('original_name')

    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.drop_column('original_name')

    # ### end Alembic commands ###
